Repository Xithrius/xithrius.cloud, pull requests merged in 2022-12, with the labels that each got.

#167 fix codeblocks
  site/lib/markdownToHtml.ts
  site/package.json
  site/tailwind.config.js
  site/yarn.lock
Labels: size/XL

#169 2023.
  site/lib/constants/todo_listing.tsx
  site/pages/index.tsx
  site/pages/todo/index.tsx
Labels: size/L

#170 Fix hydration error and flash on page load.
  site/lib/components/themeswitch.tsx
  site/pages/index.tsx
  site/styles/globals.css
Labels: size/S
