Repository Xithrius/xithrius.cloud, pull requests merged in 2022-07, with the labels that each got.

#95 Add icons proof-of-concept.
  site/pages/index.js
  site/styles/Home.module.css
Labels: size/S

#111 Fix static image links.
  site_guides/_posts/template-repositories.md
Labels: size/XS

#109 Images, more guides.
  site/package.json
  site/yarn.lock
  site_guides/@types/remark-html.d.ts
  site_guides/_posts/hello-world.md
  site_guides/_posts/preview.md
  site_guides/_posts/qol_minecraft.md
  site_guides/_posts/technology-content-creators.md
  site_guides/_posts/template-repositories.md
  site_guides/components/header.tsx
  site_guides/components/intro.tsx
  site_guides/lib/markdownToHtml.ts
  site_guides/package.json
  site_guides/public/images/posts/template-repositories/button.png
  site_guides/public/images/posts/template-repositories/list.png
  site_guides/yarn.lock
Labels: enhancement, dependencies, size/L

#129 Menu now contains text instead of icons.
  site/pages/index.jsx
  site/styles/Home.module.css
Labels: enhancement, size/M
