Repository Xithrius/xithrius.cloud, pull requests merged in 2022-04, with the labels that each got.

#19 Land the cows.
  site/public/index.html
  site/src/components/switch/Switch.css
Labels: size/S

#21 Guide improvements
  docker-compose.yml
  services/caddy/Caddyfile
  site_guides/Dockerfile
  site_guides/public/site.css
  site_guides/sass/_vendor.scss
Labels: documentation, enhancement, size/S

#29 Technology content creators.
  site_guides/.gitignore
  site_guides/guides/technology-content-creators.md
  site_guides/src/pages/index.js
  site_guides/src/styles/global.css
Labels: enhancement, size/M
